//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StretchBreak {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class StretchBreak : global::System.Configuration.ApplicationSettingsBase {
        
        private static StretchBreak defaultInstance = ((StretchBreak)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new StretchBreak())));
        
        public static StretchBreak Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("50")]
        public string timeToBreak {
            get {
                return ((string)(this["timeToBreak"]));
            }
            set {
                this["timeToBreak"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public string breakTime {
            get {
                return ((string)(this["breakTime"]));
            }
            set {
                this["breakTime"] = value;
            }
        }
    }
}
